version: '3.7'

services:
    backend:
        build: ./backend/
        volumes:
          - ./backend/app:/app
        ports:
          - 5000:5000
        links:
          - db
    db:
        build: ./db/
        volumes:
          - ./db/data:/data/db
        ports:
          - 27017:27017
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
