version: '3.7'

services:
    backend:
        build: ./backend/
        volumes:
          - ./backend/app:/app
        ports:
          - 5000:5000
        depends_on:
          - db
        networks:
          - backend
    db:
        build: ./db/
        volumes:
          - ./db/data:/data/db
        ports:
          - 27017:27017
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
        networks:
          - backend
    web:
      image: nginx
      volumes:
        - ./frontend/dist:/usr/share/nginx/html
      ports:
        - 8080:80
      networks:
        - backend
      depends_on:
        - backend

networks:
  backend:
    driver: "bridge"
